# Generated by Django 5.2.7 on 2025-10-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='aula_id',
            new_name='aluno_id',
        ),
        migrations.RemoveField(
            model_name='aula',
            name='turma_id',
        ),
        migrations.AddField(
            model_name='pagamento',
            name='tipo_pagamento',
            field=models.CharField(default='Pix', max_length=50),
        ),
        migrations.AlterField(
            model_name='aluno',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='aula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='aula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.aula'),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='frequencia',
            name='matricula_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.matricula'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='turma_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.turma'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='turma',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='TurmaAluno',
        ),
    ]
